# Generated by Django 2.2.2 on 2021-11-21 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalcrossing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='location',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='time',
        ),
    ]
